### ISSUE TITLE
Can you add conversion for yolov5

### ISSUE THREAD

**Issue by waheed0332** [gouthamvgk/coreml_conversion_hub#1]
First of all really good work.
Can you enrich this repo by adding a variation for Yolo too? Especially yoloV5?

**Comment by gouthamvgk** [comment]
> First of all really good work.
> Can you enrich this repo by adding a variation for Yolo too? Especially yoloV5?

Hi Waheed,
Currently, I am not actively developing this repo. If you want YOLO v5 models you can directly check out the ultralytics repo which has the export.py for coreml conversion. For YOLO v3 you can check out https://developer.apple.com/machine-learning/models/ . Or any pull request for adding yolo models is also welcome.

**Comment by waheed0332** [comment]
Thanks. But for YOLOv5 the don't have detection layer for exported model.

**Comment by waheed0332** [comment]
I think scripts need to be updated according to the latest tools. Can't convert efficientdet

**Comment by gouthamvgk** [comment]
> I think scripts need to be updated according to the latest tools. Can't convert efficientdet

Are you using the same versions of coremltools, onnx, torch mentioned in requirements?. Because this repo is compatible with newest version of coremltools. If so can you post the error message?

**Comment by waheed0332** [comment]
Can you share the latest requirement file?

**Comment by gouthamvgk** [comment]
> Can you share the latest requirement file?

You can refer to the README. Same as it is.
